#!/bin/bash

chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/update/update.exe"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/update/updspapi.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/update/spcustom.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/wshom.ocx"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/wscript.hlp"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/wscript.exe"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/spuninst.exe"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/cscript.exe"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/vbscript.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/spmsg.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/scrrun.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/scrobj.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/jscript.dll"
chmod 666 "$STEAM_COMPAT_DATA_PATH/pfx/dosdevices/c:/windows/syswow64/dispex.dll"
